#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WiFiCircles.Resource", IsApplication=true)]

namespace WiFiCircles
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int camLayout = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int camera_content_frame = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int camera_preview = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int channels_list_content_frame = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int networks_list_content_frame = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int row_channel = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int row_mac = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int row_rssi1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int row_rssi2 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int row_ssid = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FragmentLayoutCamera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FragmentLayoutChannels = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FragmentLayoutNetworks = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RowLayoutChannelInfo = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int RowLayoutNetworkInfo = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int device_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
